config/routes.rb
Depot::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "customers#new", :as => "signup"
  
  scope '(:locale)' do
  resources :credit_cards

  resources :customers

  resources :order_items

  resources :orders 
  
  resources :addresses


  resources :products do
    get :who_bought, on: :member
  end

  resources :sessions



  root to: "store#index", as: 'store' 
  get '/stories', to: redirect('/products')
end
end

app/models/credit_card.rb
require 'date'
class CreditCardValidator < ActiveModel::Validator
  def validate(record)
# TODO refactor it 
    yrs = []
    year_today = Date.today.strftime("%Y").to_i
    year_today.upto(year_today+10).each do |y| yrs << y.to_s; end

    unless (yrs.include?(record.exp_y.to_s) )
      record.errors[:exp_y] << 'Expiration year is invalid'
    end

    months =[]
    next_month = 1.month.from_now.strftime("%m").to_i
    next_month.upto(12).each do |m| months << m.to_s; end
  
    unless (months.include?(record.exp_m.to_s) )
      record.errors[:exp_m] << 'Expiration month is invalid'
    end
  end

end

class CreditCard < ActiveRecord::Base
  include ActiveModel::Validations

  belongs_to :order

  validates :number ,:cvv, :exp_m, :exp_y, :fname, :lname, presence: :true
  validates_numericality_of :cvv, :exp_m, :exp_y
  validates_format_of :number, with: /\A\d{16}\z/ , message: 'Invalid carn num'
  validates :cvv, :length => { is: 3 }
  validates_inclusion_of :exp_m, :in => 1..12 
  validates :exp_y, :length => { is: 4 }

  validates_with CreditCardValidator
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  before_action :set_credit_card, only: [:show, :edit, :update, :destroy]

  # GET /credit_cards/new
  def new
    @credit_card = CreditCard.new
  end

  # GET /credit_cards/1/edit
  def edit
  end

  # POST /credit_cards
  # POST /credit_cards.json
  def create
    @credit_card = CreditCard.new(credit_card_params)

    respond_to do |format|
      if @credit_card.save
        format.html { redirect_to @credit_card, notice: 'Credit card was successfully created.' }
        format.json { render action: 'show', status: :created, location: @credit_card }
      else
        format.html { render action: 'new' }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /credit_cards/1
  # PATCH/PUT /credit_cards/1.json
  def update
    respond_to do |format|
      if @credit_card.update(credit_card_params)
        format.html { redirect_to @credit_card, notice: 'Credit card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credit_cards/1
  # DELETE /credit_cards/1.json
  def destroy
    @credit_card.destroy
    respond_to do |format|
      format.html { redirect_to credit_cards_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credit_card
      @credit_card = CreditCard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def credit_card_params
      params.require(:credit_card).permit(:number, :cvv, :exp_m, :exp_y, :fname, :lname, :customer_id, :order_id)
    end
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/views/credit_cards/_form.html.erb
<%= form_for(@credit_card) do |f| %>

<%= render "shared/error_messages", :target => f.object %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :cvv %><br>
    <%= f.number_field :cvv %>
  </div>
  <div class="field">
    <%= f.label :exp_m %><br>
    <%= f.number_field :exp_m %>
  </div>
  <div class="field">
    <%= f.label :exp_y %><br>
    <%= f.number_field :exp_y %>
  </div>
  <div class="field">
    <%= f.label :fname %><br>
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label :lname %><br>
    <%= f.text_field :lname %>
  </div>
  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.text_field :customer_id %>
  </div>
  <div class="field">
    <%= f.label :order_id %><br>
    <%= f.text_field :order_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/credit_cards/edit.html.erb
<h1>Editing credit_card</h1>

<%= render 'form' %>

<%= link_to 'Show', @credit_card %> |
<%= link_to 'Back', credit_cards_path %>

app/views/credit_cards/index.html.erb
<h1>Listing credit_cards</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Cvv</th>
      <th>Exp m</th>
      <th>Exp y</th>
      <th>Fname</th>
      <th>Lname</th>
      <th>Customer</th>
      <th>Order</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @credit_cards.each do |credit_card| %>
      <tr>
        <td><%= credit_card.number %></td>
        <td><%= credit_card.cvv %></td>
        <td><%= credit_card.exp_m %></td>
        <td><%= credit_card.exp_y %></td>
        <td><%= credit_card.fname %></td>
        <td><%= credit_card.lname %></td>
        <td><%= credit_card.customer %></td>
        <td><%= credit_card.order %></td>
        <td><%= link_to 'Show', credit_card %></td>
        <td><%= link_to 'Edit', edit_credit_card_path(credit_card) %></td>
        <td><%= link_to 'Destroy', credit_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Credit card', new_credit_card_path %>

app/views/credit_cards/new.html.erb
<h1>New credit_card</h1>

<%= render 'form' %>

<%= link_to 'Back', credit_cards_path %>

app/views/credit_cards/show.html.erb
<%= render "shared/notice" %>

<p>
  <strong>Number:</strong>
  <%= @credit_card.number %>
</p>

<p>
  <strong>Cvv:</strong>
  <%= @credit_card.cvv %>
</p>

<p>
  <strong>Exp m:</strong>
  <%= @credit_card.exp_m %>
</p>

<p>
  <strong>Exp y:</strong>
  <%= @credit_card.exp_y %>
</p>

<p>
  <strong>Fname:</strong>
  <%= @credit_card.fname %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @credit_card.lname %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @credit_card.customer %>
</p>

<p>
  <strong>Order:</strong>
  <%= @credit_card.order %>
</p>

<%= link_to 'Edit', edit_credit_card_path(@credit_card) %> |
<%= link_to 'Back', credit_cards_path %>