config/routes.rb
Depot::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "customers#new", :as => "signup"
  
  scope '(:locale)' do
  resources :credit_cards

  resources :customers

  resources :order_items

  resources :orders 
  
  resources :addresses


  resources :products do
    get :who_bought, on: :member
  end

  resources :sessions



  root to: "store#index", as: 'store' 
  get '/stories', to: redirect('/products')
end
end

app/models/customer.rb
require 'active_support/core_ext/object/try.rb'

class Customer < ActiveRecord::Base
  has_many :ratings
  has_many :orders

  has_secure_password

  validates :email, :first_name, :last_name, :password_digest, presence: :true
  validates :email, uniqueness: true, format: { with: /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/ }
  validates_inclusion_of :role, in: %w(admin user), allow_nil: true
  
  before_create :set_user_role

  def name
    first_name + " " + last_name
  end

  def admin?
    true if role.eql? "admin"
  end

  def set_user_role
    self.role = 'user'
  end

  def rate(product)
  	products = []
    orders.each do |o|
      o.order_items.each do |oi|
        products << oi.product_id
      end
    end
    ratings = Rating.where("customer_id = #{self.id} AND product_id = #{product.id}")
# try instead on unless not
    unless ratings.empty?
     ratings.each do |r| 
       products.delete(r.product_id) if products.include? r.product_id
     end
    end
    puts "#{ratings}"
    # list of products that can be rated 
    products

    if products.include? product.id
# create new rating
      true
    else
# return error
     false
    end
  end 
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  skip_before_filter :authorize, only: [:new, :create]

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
  @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        session[:customer_id] = @customer.id

        format.html { redirect_to store_path }
        format.json { render json: @customer, status: :created,
          location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors,
          status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :ok }
    end
  end

   def customer_params
      params.require(:customer).permit(:email, :first_name, :last_name, :password, :password_confirmation)
    end
end

app/views/customers/_customer.html.erb
<%= link_to customer.name, customer%>
<div>Email: <%= customer.email %></div>
<div>Role: <%= customer.role %></div>
<div>Registered: <%= customer.created_at %></div>

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>

<%= render "shared/error_messages", :target => f.object %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/new.html.erb
<h1>Signup!</h1>

<%= render 'form' %>

<h2> <- or login...</h2>


<%= link_to 'Back', order_path(@order) %>

app/views/customers/show.html.erb
<%= render "shared/notice" %>
<%= render @customer %>