config/routes.rb
Depot::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "customers#new", :as => "signup"
  
  scope '(:locale)' do
  resources :credit_cards

  resources :customers

  resources :order_items

  resources :orders 
  
  resources :addresses


  resources :products do
    get :who_bought, on: :member
  end

  resources :sessions



  root to: "store#index", as: 'store' 
  get '/stories', to: redirect('/products')
end
end

app/models/order.rb
class Order < ActiveRecord::Base

  # validates_inclusion_of :state, in: %w(in_progress complited shipped), allow_blank: true

  has_many :order_items, dependent: :destroy
  belongs_to :customer
  belongs_to :shipp_address, class_name: "Address"
  belongs_to :bill_address, class_name: "Address"

# TODO update after order_item added
  after_find :count_price
  before_create :set_status

  scope :_new, -> {where("state = 'new'")}
  scope :completed, -> {where("state = 'completed'")}

  def count_price
    self.total_price = OrderItem.where(order_id: self.id).sum("price")
    save
  end

  def set_status
    self.state = 'new'
  end

  def set_customer(customer)
    self.customer_id = customer.id if customer
  end
   
  def complete_order(customer)
    self.completed_at = Date.today
    self.state = "completed"
    set_customer(customer)
    save
  end


  def add_product(product) 
    current_item = order_items.find_by_product_id(product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = order_items.create(product_id: product.id)
    end
    # TODO move to callbacks of OrderItem
    product.in_stock-=1
    product.save

    current_item
  end

  def add_address(address)
    self.bill_address = address
    self.shipp_address = address
    save
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  skip_before_filter :authorize, only: [:create, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = @current_customer.orders.completed.paginate page: params[:page], order: 'created_at desc', per_page: 10
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    if @order.order_items.empty?
      redirect_to store_url, notice: "Your cart is empty"
      return
    end 
    begin
      @order = Order.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_path, notice: 'Invalid cart'
    else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @order }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    session[:order_id] = nil

    respond_to do |format|
      format.html { redirect_to store_url, notice: 'Your cart is empty now!' }
      format.json { head :ok }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit()
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>

<%= render "shared/error_messages", :target => f.object %>

  <div class="field">
    <%= f.label :bill_address %><br>
    <%= f.text_field :bill_address %>
  </div>
  <div class="field">
    <%= f.label :shipp_address %><br>
    <%= f.text_field :shipp_address %>
  </div>
  <div class="actions">
     <%= submit_tag("Done!") %>
  </div>
  
<% end %>

app/views/orders/_order.html.erb
<% unless order.order_items.empty? %>
<div class="cart_title">Your cart</div>
<table>
  <%= render(order.order_items) %>
  <tr class="total_line">
    <td colspan="2">Total:</td>
    <td class="total_cell"><%= number_to_currency(order.total_price) %></td>
  </tr>
</table>
<% end %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>
<table> 
  
<% @orders.each do |order| %>
  <tr>
    <%= render order %>
    <td><%= order.customer.name %></td>
    <td><%= order.shipp_address %></td>
    <td><%= order.customer.email %></td>
     </tr>
 <% end %>
 </table>
 <br />
<p><%= will_paginate @orders %></p>

app/views/orders/new.html.erb
<h1>Fill form</h1>

<%= render 'form' %>

<%= link_to 'Back', store_path %>

app/views/orders/show.html.erb
<%= render "shared/notice" %>

<%= render @order %>

<p>Bill address: <%= @order.bill_address %></p>
<p>Ship address: <%= @order.shipp_address %></p>

<p>Status: <%= @order.state %></p>
<p>completed_at: <%= @order.completed_at %></p>

<%= button_to "Proceed", new_address_path(@order.bill_address), method: :get %>
<%= link_to 'Back to store', store_path %>  