config/routes.rb
Depot::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "customers#new", :as => "signup"
  
  scope '(:locale)' do
  resources :credit_cards

  resources :customers

  resources :order_items

  resources :orders 
  
  resources :addresses


  resources :products do
    get :who_bought, on: :member
  end

  resources :sessions



  root to: "store#index", as: 'store' 
  get '/stories', to: redirect('/products')
end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base

  validates_numericality_of :quantity, :price
  belongs_to :product
  belongs_to :order

  before_save :count_price
  after_destroy :back_product_to_stock

  def count_price
    self.price = (product.price * quantity).to_f
  end

  def back_product_to_stock
    product.in_stock += self.quantity
    product.save
  end

  def decrease_product_quantity
    product.in_stock += 1
    product.save
  end



  # def check_it
  #  if self.quantity > 1
  #     self.quantity -= 1
  #     self.save
  #     # TODO check if its fine??  
  #     self.decrease_product_quantity
  #     false
  #  else
  #    self.back_product_to_stock
  #    true
  #  end
  # end

end

  

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  skip_before_filter :authorize
  before_action :set_order_item, only: [:show, :edit, :update, :destroy]

  # GET /order_items
  # GET /order_items.json
  def index
    @order_items = OrderItem.all
  end

  # POST /order_items
  # POST /order_items.json
  def create
    product = Product.find(params[:product_id])
    @order_item = @order.add_product(product)
    respond_to do |format|
      if @order_item.save
        format.html { redirect_to store_url }
        format.json { render json: @order_item, status: :created, location: @order_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @order_item.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /order_items/1
  # DELETE /order_items/1.json
  def destroy
  # TODO move it somewhere
    if @order_item.quantity > 1
      @order_item.quantity -= 1
      @order_item.save
      
      @order_item.decrease_product_quantity
    else
      @order_item.destroy
    end 

    respond_to do |format|
      format.html { redirect_to store_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_item
      @order_item = OrderItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_item_params
      params.require(:order_item).permit(:product_id, :order_id, :price, :quantity)
    end
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/views/order_items/_form.html.erb
<%= form_for(@order_item) do |f| %>

<%= render "shared/error_messages", :target => f.object %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :order_id %><br>
    <%= f.number_field :order_id %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/order_items/_order_item.html.erb
<% if order_item == @current_item %>
<tr id="current_item">
<% else %>
<tr>
<% end %>
  <td><%= order_item.quantity %>x </td>
  <td><%= order_item.product.title %></td>
  <td class="item_price"><%= number_to_currency(order_item.price) %></td>
  <td><%= link_to ' X', order_item, method: :delete %></td>
</tr>

app/views/order_items/create.js.erb
$('#cart').html("<%=j render @order %>");

$('#current_item').css({'background-color':'#88ff88'}).animate({'background-color':'#114411'}, 1000);

app/views/order_items/index.html.erb
<h1>Listing order_items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Order</th>
      <th>Price</th>
      <th>Quantity</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @order_items.each do |order_item| %>
      <tr>
        <td><%= order_item.product_id %></td>
        <td><%= order_item.order_id %></td>
        <td><%= order_item.price %></td>
        <td><%= order_item.quantity %></td>
        <td><%= link_to 'Show', order_item %></td>
        <td><%= link_to 'Edit', edit_order_item_path(order_item) %></td>
        <td><%= link_to 'Destroy', order_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order item', new_order_item_path %>

app/views/order_items/new.html.erb
<h1>New order_item</h1>

<%= render 'form' %>

<%= link_to 'Back', order_items_path %>

app/views/order_items/show.html.erb
<%= render "shared/notice" %>
<p>
  <strong>Product:</strong>
  <%= @order_item.product_id %>
</p>

<p>
  <strong>Order:</strong>
  <%= @order_item.order_id %>
</p>

<p>
  <strong>Price:</strong>
  <%= @order_item.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @order_item.quantity %>
</p>

<%= link_to 'Edit', edit_order_item_path(@order_item) %> |
<%= link_to 'Back', order_items_path %>